#microservice configuration
spring.application.name=ms-catalogo
server.port = 8082

#Database configuration
spring.mongodb.uri=mongodb://mongo-db:27017/ms_catalog_db

#JWT configuration
jwt.secret=8ba7aadce36f56ad91804fc67378f0975d6a2f732dd68d27a2e152994eca841
jwt.expiration=86400000

#eureka configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
